### ISSUE TITLE
 Ruby version problem

### ISSUE THREAD

**Issue by alekzernov** [johnfairh/RubyGateway#38]
I have swift project.  в нем $LOAD_PATH :
/Library/Ruby/Site/2.6.0
/Library/Ruby/Site/2.6.0/x86_64-darwin20
/Library/Ruby/Site/2.6.0/universal-darwin20
/Library/Ruby/Site
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/x86_64-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby/2.6.0/universal-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/vendor_ruby
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/x86_64-darwin20
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin20
In termenal 
/Users/alexandr/.rvm/rubies/ruby-2.7.0/lib/ruby/site_ruby/2.7.0
/Users/alexandr/.rvm/rubies/ruby-2.7.0/lib/ruby/site_ruby/2.7.0/x86_64-darwin20
/Users/alexandr/.rvm/rubies/ruby-2.7.0/lib/ruby/site_ruby
/Users/alexandr/.rvm/rubies/ruby-2.7.0/lib/ruby/vendor_ruby/2.7.0
/Users/alexandr/.rvm/rubies/ruby-2.7.0/lib/ruby/vendor_ruby/2.7.0/x86_64-darwin20
/Users/alexandr/.rvm/rubies/ruby-2.7.0/lib/ruby/vendor_ruby
/Users/alexandr/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0
/Users/alexandr/.rvm/rubies/ruby-2.7.0/lib/ruby/2.7.0/x86_64-darwin20

How to make it fashionable to look from the ruby ​​project in the same place and from the terminal?

**Comment by johnfairh** [comment]
They are different because Xcode does not see the RVM overrides done in `.bash_profile`.

I assume you are using Xcode with an `.xcodeproj`, and you want Xcode to use RVM Ruby 2.7?

You need to set Xcode flags to point to your RVM Ruby, see [here](https://github.com/johnfairh/RubyGateway#installation) leading to [here](https://github.com/johnfairh/CRuby#xcode).

It's pretty messy - I don't know how to make it easier to do in Xcode 😢

**Comment by johnfairh** [comment]
Closing, answered.
